services:
  vogon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vogon
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/src/db
    # environment:
    #   - TMDB_API_KEY=
    #   - FANART_API_KEY=
    #   - THEPOSTERDB_EMAIL=
    #   - THEPOSTERDB_PASSWORD=
    #   - REMOVE_OVERLAYS=true